# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
title: Explainers
email: jaanerik.pihel@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome2 description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/github-blog" # the subpath of your site, e.g. /blog
url: "https://jaanerik.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username: jaanerik 

head_scripts:
# - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
#  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML-full

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.27.3"
minimal_mistakes_skin: "dark" #"default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
#remote_theme: "jekyll/minima@1e8a445"
timezone: Europe/Tallinn
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll gravatar

author:
  name     : "Jaan Erik Pihel"
  #gravatar   : 00d19e2f13f629da5e5f05682b76f78f96293694be22ca2a1611aa47e9a4ff91
  bio      : "My background is in data science and mathematics."
  location : "Tartu, Estonia"
  avatar   : "https://gravatar.com/avatar/00d19e2f13f629da5e5f05682b76f78f96293694be22ca2a1611aa47e9a4ff91?v=1755933515000&size=256&d=initials"


defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      toc: true
      toc_sticky: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
